### ISSUE TITLE
Krill protocol carousel gradually becomes 'offset' with each step

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium#229]
The step carousel for krill seems to be slightly offset with each click of "OK." The offset seems gets 'worse' with each step. See the picture below that the "OK" is somehow off the browser. Refreshing the page fixes the issue temporarily.
![screenshot 1](https://user-images.githubusercontent.com/10437900/27814371-c04e8da8-6030-11e7-90cf-6f537f664218.png)

**Comment by klavins** [comment]
Fixed quite some time ago.
