### ISSUE TITLE
make overnight suspension took in wrong object type

### ISSUE THREAD

**Issue by ayeshasal** [klavinslab/aquarium#248]
this is talking about [this job](http://52.27.43.242/krill/log?job=42451)

josh's plate (item: [99605](http://52.27.43.242/items/99605)), which had an object type of "E coli plate of Plasmid," was used as an input for this job, even though it shouldn't have been because it's the wrong object type. there was an overnight suspension created from this plate (but no steps were shown on screen because the steps only show up if the input is a glycerol stock or a checked e coli plate of plasmid, due to the way i wrote the protocol).

this issue likely originated from "Check Plate"--josh's plate was imaged multiple times, which (i think) messed with the way the protocol changed the object type of the plate from "E coli plate of Plasmid" to "Check E coli plate of Plasmid" (though i'm not exactly sure why or how). compare josh's plate to arjun's (item: [99450](http://52.27.43.242/items/99450)), which also went through "Check Plate" but came out the other side with the correct object type (checked e coli plate of plasmid). arjun and josh's jobs were batched together for the overnight suspension, but arjun's errored out (correctly; this was an issue quickly fixed inside the overnight suspension protocol) and josh's didn't, which makes me think that the "Check Plate" protocol and "Make Overnight Suspension" protocols are working at least somewhat correctly, but, somehow, josh's plate slipped through when it shouldn't have. 

For reference: 
[the "check plate" job for josh's plate](http://52.27.43.242/krill/log?job=42347) 
[the "check plate" job for arjun's plate](http://52.27.43.242/krill/log?job=42447)
josh's plan number: 44
arjun's plan number: 354

**Comment by bjkeller** [comment]
This appears to be a protocol issue, and I'm closing it.
