### ISSUE TITLE
What is this text field in the Samples list view?

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium#313]
On the left edge of the screen...

<img width="407" alt="screen shot 2018-08-27 at 12 19 31 pm" src="https://user-images.githubusercontent.com/7586251/44680791-9498f780-a9f3-11e8-87af-37f3f888dde6.png">

**Comment by Gamemackerel** [comment]
This is so that you can give your samples a short tag for your personal organizational needs.

**Comment by dvnstrcklnd** [comment]
Oh, OK.

**Comment by bjkeller** [comment]
closing this
