### ISSUE TITLE
Syntax in op.temporary[] dictionaries is different in test than in real manager scenario[BUG]

### ISSUE THREAD

**Issue by XavaarQ** [klavinslab/aquarium#390]
**Describe the bug**
##If you have this
key = "key"
table operations.start_table
.get(key, type: 'number', heading: "example", default: -1) 
.end_table

##This will happen while testing
print(op.temporary[:key].to_f) => -1.0
print(op.temporary["key"].to_f) => 0.0

#But when run the exact same protocol in the real manager scenario this will happen
print(op.temporary[:key].to_f) => 0.0
print(op.temporary["key"].to_f) => -1.0

**To Reproduce**
1. Go to 'Nursery Server => Developer => A-Duckweed => Duckweed Culture Split (Version 109577)
2. Test the Protocol 
3. Notice the 3rd to last Show block, lines 163 to 173 in the protocol
4. Run this same protocol manually through the Design and Manager tabs, enter what ever number you want when prompted, Notice the reversal of what happened in the test scenario

**Expected behavior**
I expect this to function the same in both the Text and production versions

**Screenshots**
![image](https://user-images.githubusercontent.com/51213691/75920374-169d8400-5e14-11ea-82ff-0867133480da.png)
![image](https://user-images.githubusercontent.com/51213691/75920449-3af96080-5e14-11ea-9a6b-98ba601c5dec.png)
![image](https://user-images.githubusercontent.com/51213691/75920582-87dd3700-5e14-11ea-91b7-97d1c28933ec.png)

**Computer/Device (please complete the following information):**

**Additional context**

**Comment by bjkeller** [comment]
Thanks for the report. I changed the handling of table inputs in the test execution so that it works the same way as normal execution.  This won't show up in production until the changes are pushed.

A couple of things to note:
1. The default behavior during normal operation is to convert the key to a symbol. 
    So, `:key` instead of`"key"`.

    I'll admit it is a bit confusing to give the key as a string and have to use a symbol to get the value, but I expect changing it now would break a lot of protocols. So, I suggest always using a symbol as a key to keep this straight when you are coding.  Incidentally, if you have a string variable `s` that you want use as a key, you can convert it by using `s.to_sym`.

2. The normal behavior is that number inputs are converted to floating point values, but the test behavior was different. 
    Along the same lines as the key type, I would suggest always giving the default value as a floating point number.
   So, `-1.0` instead of `-1`.

**Comment by bjkeller** [comment]
Just to be clear this won't appear in biofab production until the system is updated.
